// This file was generated by img2gb, DO NOT EDIT

#ifndef _CREDITSMAP_H
#define _CREDITSMAP_H

extern const UINT8 TILEMAP_CREDITS[];
#define TILEMAP_CREDITS_WIDTH 20
#define TILEMAP_CREDITS_HEIGHT 18


#endif
