// This file was generated by img2gb, DO NOT EDIT

#ifndef _KITCHEN_H
#define _KITCHEN_H

extern const UINT8 TILESET_KITCHEN[];
#define TILESET_KITCHEN_TILE_COUNT 78

extern const UINT8 TILEMAP_KITCHEN[];
#define TILEMAP_KITCHEN_WIDTH 20
#define TILEMAP_KITCHEN_HEIGHT 18

#endif
