// This file was generated by img2gb, DO NOT EDIT

#ifndef _TILESET_H
#define _TILESET_H

extern const UINT8 TILESETSP[];
#define TILESET_TILE_COUNTSP 140

extern const UINT8 TILEMAPSP[];
#define TILEMAP_WIDTHSP 20
#define TILEMAP_HEIGHTSP 18

#endif
