// This file was generated by img2gb, DO NOT EDIT

#ifndef _TITLESCREEN_H
#define _TITLESCREEN_H

extern const UINT8 TILESET_SCREEN[];
#define TILESET_SCREEN_TILE_COUNT 205

extern const UINT8 TILEMAP_SCREEN[];
#define TILEMAP_SCREEN_WIDTH 20
#define TILEMAP_SCREEN_HEIGHT 18

#endif
